# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.define "centos" do |centos|
    centos.vm.box = "bento/centos-7.2"
  end

  config.vm.define "debian" do |debian|
    debian.vm.box = "debian/jessie64"
  end
end
