# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.2"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder "../source", "/opt/source"
  
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.sudo = true
  end  
end
